version: "3.7"
services:
  app:
    image: "leoozeballos/concesionaria:latest"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/concesionaria"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=docker"
    networks:
      - concesionaria
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "concesionaria"
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - concesionaria

networks:
  concesionaria:
    driver: bridge